export const default_labels = {
	// LAYOUT
	container: "Container",
	row: "Row",
	column: "Column",
	column_break: "Column Break",
	media_object: "Media Object",

	// COMPONENTS
	alert: "Alert",
	tabs: "Tabs",
	tab: "Tab",
	tabPane: "Tab Pane",
	badge: "Badge",
	button: "Button",
	button_group: "Button Group",
	button_toolbar: "Button Toolbar",
	card: "Card",
	card_container: "Card Container",
	collapse: "Collapse",
	dropdown: "Dropdown",
	dropdown_menu: "Dropdown Menu",
	dropdown_item: "Dropdown Item",

	// MEDIA
	image: "Image",
	video: "Video",

	// TYPOGRAPHY
	text: "Text",

	// BASIC
	header: "Header",
	paragraph: "Paragraph",
	link: "Link",
	list: "Simple List",

	// FORMS
	form: "Form",
	input: "Input",
	file_input: "File",
	form_group_input: "Form Group",
	input_group: "Input group",
	textarea: "Textarea",
	select: "Select",
	select_option: "- Select option -",
	option: "Option",
	label: "Label",
	checkbox: "Checkbox",
	radio: "Radio",
	trait_method: "Method",
	trait_enctype: "Encoding Type",
	trait_multiple: "Multiple",
	trait_action: "Action",
	trait_state: "State",
	trait_id: "ID",
	trait_for: "For",
	trait_name: "Name",
	trait_placeholder: "Placeholder",
	trait_value: "Value",
	trait_required: "Required",
	trait_type: "Type",
	trait_options: "Options",
	trait_checked: "Checked",
	type_text: "Text",
	type_email: "Email",
	type_password: "Password",
	type_number: "Number",
	type_date: "Date",
	type_hidden: "Hidden",
	type_submit: "Submit",
	type_reset: "Reset",
	type_button: "Button",
};