export const default_blocks = {
	default: true,
	text: true,
	link: true,
	image: true,
	// LAYOUT
	container: true,
	row: true,
	column: true,
	column_break: true,
	media_object: true,
	// COMPONENTS
	alert: true,
	tabs: true,
	badge: true,
	button: true,
	button_group: true,
	button_toolbar: true,
	card: true,
	card_container: true,
	collapse: true,
	dropdown: true,
	video: true,
	// TYPOGRAPHY
	header: true,
	paragraph: true,
	// BASIC
	list: true,
	// FORMS
	form: true,
	input: true,
	form_group_input: true,
	input_group: true,
	textarea: true,
	select: true,
	label: true,
	checkbox: true,
	radio: true,
};
