export const variables = [
  {
    id: "primary",
    name: "Primary",
    value: "#007bff",
    variable: "bs-primary",
    type: "HEXcolor",
    category: "Colors",
  },
  {
    id: "secondary",
    name: "Secondary",
    value: "#6c757d",
    variable: "bs-secondary",
    type: "HEXcolor",
    category: "Colors",
  },
  {
    id: "primaryRGB",
    name: "Primary RGB",
    value: "13,110,253",
    variable: "bs-primary-rgb",
    type: "RGBcolor",
    category: "Colors",
  },
  {
    id: "secondaryRGB",
    name: "Secondary RGB",
    value: "108, 117, 125",
    variable: "bs-secondary-rgb",
    type: "RGBcolor",
    category: "Colors",
  },

  {
    id: "success",
    name: "Success",
    value: "#28a745",
    variable: "bs-success",
    type: "HEXcolor",
    category: "Colors",
  },
  {
    id: "danger",
    name: "Danger",
    value: "#dc3545",
    variable: "bs-danger",
    type: "HEXcolor",
    category: "Colors",
  },
  {
    id: "warning",
    name: "Warning",
    value: "#ffc107",
    variable: "bs-warning",
    type: "HEXcolor",
    category: "Colors",
  },
  {
    id: "info",
    name: "Info",
    value: "#17a2b8",
    variable: "bs-info",
    type: "HEXcolor",
    category: "Colors",
  },
  {
    id: "light",
    name: "Light",
    value: "#f8f9fa",
    variable: "bs-light",
    type: "HEXcolor",
    category: "Colors",
  },
  {
    id: "dark",
    name: "Dark",
    value: "#343a40",
    variable: "bs-dark",
    type: "HEXcolor",
    category: "Colors",
  },
  {
    id: "font-family-base",
    name: "Font Family Base",
    value:
      "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    variable: "bs-font-family-base",
    type: "TEXTInput",
    category: "Typography",
  },
  {
    id: "font-size-base",
    name: "Font Size Base",
    value: "1rem",
    variable: "bs-font-size-base",
    type: "TEXTInput",
    category: "Typography",
  },
  {
    id: "line-height-base",
    name: "Line Height Base",
    value: "1.5",
    variable: "bs-line-height-base",
    type: "TEXTInput",
    category: "Typography",
  },
];
